name: 'General Automation'
on:
  push:
    branches: [master, next]
  pull_request_target:
    branches: next

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  approve-pr-dependabot:
    name: Approve PR (dependabot)
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1.7.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
  publish-docs:
    name: Publish Docs
    if: github.event_name == 'push' && github.repository_owner == 'ZPTXDev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npx typedoc src/index.ts --name "${{ github.event.repository.name }} (${{ github.ref_name }})"
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          folder: docs
          repository-name: ZPTXDev/docs
          target-folder: ${{ github.event.repository.name }}${{ github.ref_name != 'master' && format('/{0}', github.ref_name) || '' }}
          commit-message: 'docs: update docs for ${{ github.event.repository.name }}/${{ github.ref_name }}'
          git-config-name: zptx-bot
          git-config-email: bot@zptx.dev
          clean: false
  semantic-release:
    name: Semantic Release
    if: github.event_name == 'push' && github.repository_owner == 'ZPTXDev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              'master',
              {name: 'next', prerelease: true}
            ]
          extra_plugins: |
            @semantic-release/git
            https://github.com/ZPTXDev/semantic-release-github-milestones#master
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
